server.port=8080
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.url=jdbc:mariadb://edumgt.cg0ugoglztrn.ap-northeast-2.rds.amazonaws.com/mockinv
spring.datasource.username=edumgt
spring.datasource.password=nero8653
spring.jpa.hibernate.ddl-auto= create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
spring.jpa.generate-ddl=false
