apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-mock-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-mock-app
  template:
    metadata:
      labels:
        app: crypto-mock-app
    spec:
      containers:
        - name: app
          image: java-crypto-mock-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: crypto-mock-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: crypto-mock-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: crypto-mock-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crypto-mock-secret
                  key: SPRING_DATASOURCE_PASSWORD
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
