apiVersion: v1
kind: Secret
metadata:
  name: crypto-mock-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: mockinv1234
  MARIADB_ROOT_PASSWORD: root123456
  MARIADB_PASSWORD: mockinv1234
